// Exact SQLite schema profiles used by the COLMAP database adapter.
//
// The stock definitions are reimplemented from COLMAP's BSD-3-Clause
// database_sqlite.cc at the pinned revisions listed below. The MAXX definition
// is reimplemented from the user-owned colmap_mod repository at de15b08a.
// Profile matching compares a canonical structural description generated by
// SQLite itself; user_version alone is never treated as schema identity.
#pragma once

#include <cstdint>
#include <string>
#include <vector>

struct ColmapDbProfileSpec {
    const char *name;
    const char *source_revision;
    int32_t application_id;
    int32_t user_version;
    bool typed_descriptors;
    bool generalized_pose_priors;
    bool recovered_two_view_cameras;
    bool maxx_extensions;
    const char *schema_sql;
    bool requires_maxx_schema_row;
};

inline const std::vector<ColmapDbProfileSpec> &colmap_db_profile_specs() {
    static const char *common = R"SQL(
CREATE TABLE rigs(
  rig_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ref_sensor_id INTEGER NOT NULL,
  ref_sensor_type INTEGER NOT NULL);
CREATE UNIQUE INDEX rig_ref_sensor_assignment
  ON rigs(ref_sensor_id, ref_sensor_type);
CREATE TABLE rig_sensors(
  rig_id INTEGER NOT NULL,
  sensor_id INTEGER NOT NULL,
  sensor_type INTEGER NOT NULL,
  sensor_from_rig BLOB,
  FOREIGN KEY(rig_id) REFERENCES rigs(rig_id) ON DELETE CASCADE);
CREATE UNIQUE INDEX rig_sensor_assignment
  ON rig_sensors(sensor_id, sensor_type);
CREATE TABLE cameras(
  camera_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  model INTEGER NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  params BLOB,
  prior_focal_length INTEGER NOT NULL);
CREATE TABLE frames(
  frame_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  rig_id INTEGER NOT NULL,
  FOREIGN KEY(rig_id) REFERENCES rigs(rig_id) ON DELETE CASCADE);
CREATE TABLE frame_data(
  frame_id INTEGER NOT NULL,
  data_id INTEGER NOT NULL,
  sensor_id INTEGER NOT NULL,
  sensor_type INTEGER NOT NULL,
  FOREIGN KEY(frame_id) REFERENCES frames(frame_id) ON DELETE CASCADE);
CREATE UNIQUE INDEX frame_sensor_assignment
  ON frame_data(data_id, sensor_type);
CREATE TABLE images(
  image_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL UNIQUE,
  camera_id INTEGER NOT NULL,
  CONSTRAINT image_id_check
    CHECK(image_id >= 0 and image_id < 2147483647),
  FOREIGN KEY(camera_id) REFERENCES cameras(camera_id));
CREATE UNIQUE INDEX index_name ON images(name);
)SQL";
    static const char *pose_313 = R"SQL(
CREATE TABLE pose_priors(
  image_id INTEGER PRIMARY KEY NOT NULL,
  position BLOB,
  coordinate_system INTEGER NOT NULL,
  position_covariance BLOB,
  FOREIGN KEY(image_id) REFERENCES images(image_id) ON DELETE CASCADE);
)SQL";
    static const char *pose_modern = R"SQL(
CREATE TABLE pose_priors(
  pose_prior_id INTEGER PRIMARY KEY NOT NULL,
  corr_data_id INTEGER NOT NULL,
  corr_sensor_id INTEGER NOT NULL,
  corr_sensor_type INTEGER NOT NULL,
  position BLOB,
  position_covariance BLOB,
  gravity BLOB,
  coordinate_system INTEGER NOT NULL);
CREATE UNIQUE INDEX pose_prior_data_assignment
  ON pose_priors(corr_data_id, corr_sensor_id, corr_sensor_type);
)SQL";
    static const char *keypoints = R"SQL(
CREATE TABLE keypoints(
  image_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  FOREIGN KEY(image_id) REFERENCES images(image_id) ON DELETE CASCADE);
)SQL";
    static const char *descriptors_313 = R"SQL(
CREATE TABLE descriptors(
  image_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  FOREIGN KEY(image_id) REFERENCES images(image_id) ON DELETE CASCADE);
)SQL";
    static const char *descriptors_modern = R"SQL(
CREATE TABLE descriptors(
  image_id INTEGER PRIMARY KEY NOT NULL,
  type INTEGER NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  FOREIGN KEY(image_id) REFERENCES images(image_id) ON DELETE CASCADE);
)SQL";
    static const char *matches = R"SQL(
CREATE TABLE matches(
  pair_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB);
)SQL";
    static const char *geometry_10 = R"SQL(
CREATE TABLE two_view_geometries(
  pair_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  config INTEGER NOT NULL,
  F BLOB,
  E BLOB,
  H BLOB,
  qvec BLOB,
  tvec BLOB);
)SQL";
    static const char *geometry_12 = R"SQL(
CREATE TABLE two_view_geometries(
  pair_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  config INTEGER NOT NULL,
  F BLOB,
  E BLOB,
  H BLOB,
  qvec BLOB,
  tvec BLOB,
  camera1 BLOB,
  camera2 BLOB);
)SQL";
    static const std::string stock_313 =
        std::string(common) + pose_313 + keypoints + descriptors_313 +
        matches + geometry_10;
    static const std::string stock_411 =
        std::string(common) + pose_modern + keypoints + descriptors_modern +
        matches + geometry_10;
    static const std::string stock_current =
        std::string(common) + pose_modern + keypoints + descriptors_modern +
        matches + geometry_12;
    static const std::string maxx = R"SQL(
CREATE TABLE maxx_schema_info(
  schema_version INTEGER PRIMARY KEY NOT NULL,
  minimum_reader_version INTEGER NOT NULL,
  producer_version TEXT NOT NULL,
  producer_commit TEXT NOT NULL);
CREATE TABLE rigs(
  rig_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ref_sensor_id INTEGER NOT NULL,
  ref_sensor_type INTEGER NOT NULL);
CREATE UNIQUE INDEX rig_ref_sensor_assignment
  ON rigs(ref_sensor_id, ref_sensor_type);
CREATE TABLE rig_sensors(
  rig_id INTEGER NOT NULL,
  sensor_id INTEGER NOT NULL,
  sensor_type INTEGER NOT NULL,
  sensor_from_rig BLOB,
  FOREIGN KEY(rig_id) REFERENCES rigs(rig_id) ON DELETE CASCADE);
CREATE UNIQUE INDEX rig_sensor_assignment
  ON rig_sensors(sensor_id, sensor_type);
CREATE TABLE cameras(
  camera_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  model INTEGER NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  params BLOB,
  prior_focal_length INTEGER NOT NULL);
CREATE TABLE frames(
  frame_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  rig_id INTEGER NOT NULL,
  FOREIGN KEY(rig_id) REFERENCES rigs(rig_id) ON DELETE CASCADE);
CREATE TABLE frame_data(
  frame_id INTEGER NOT NULL,
  data_id INTEGER NOT NULL,
  sensor_id INTEGER NOT NULL,
  sensor_type INTEGER NOT NULL,
  FOREIGN KEY(frame_id) REFERENCES frames(frame_id) ON DELETE CASCADE);
CREATE UNIQUE INDEX frame_sensor_assignment
  ON frame_data(data_id, sensor_type);
CREATE TABLE images(
  image_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL UNIQUE,
  camera_id INTEGER NOT NULL,
  time_id INTEGER NULL,
  CONSTRAINT image_id_check
    CHECK(image_id >= 0 and image_id < 2147483647),
  FOREIGN KEY(camera_id) REFERENCES cameras(camera_id));
CREATE UNIQUE INDEX index_name ON images(name);
CREATE TABLE videos(
  video_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL UNIQUE,
  source_path TEXT,
  content_hash TEXT,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  num_frames INTEGER NOT NULL,
  fps REAL NOT NULL,
  duration_seconds REAL NOT NULL,
  codec_name TEXT,
  sync_group TEXT);
CREATE UNIQUE INDEX index_video_name ON videos(name);
CREATE TABLE video_frames(
  video_id INTEGER NOT NULL,
  image_id INTEGER NOT NULL UNIQUE,
  frame_id INTEGER NOT NULL,
  pts_seconds REAL,
  time_id INTEGER,
  PRIMARY KEY(video_id, frame_id),
  FOREIGN KEY(video_id) REFERENCES videos(video_id) ON DELETE CASCADE,
  FOREIGN KEY(image_id) REFERENCES images(image_id) ON DELETE CASCADE);
CREATE INDEX index_video_frame_image ON video_frames(image_id);
CREATE TABLE pose_priors(
  pose_prior_id INTEGER PRIMARY KEY NOT NULL,
  corr_data_id INTEGER NOT NULL,
  corr_sensor_id INTEGER NOT NULL,
  corr_sensor_type INTEGER NOT NULL,
  position BLOB,
  position_covariance BLOB,
  gravity BLOB,
  coordinate_system INTEGER NOT NULL,
  rotation BLOB,
  rotation_covariance BLOB,
  pose_covariance BLOB);
CREATE UNIQUE INDEX pose_prior_data_assignment
  ON pose_priors(corr_data_id, corr_sensor_id, corr_sensor_type);
CREATE TABLE image_qualities(
  image_id INTEGER PRIMARY KEY NOT NULL,
  quality REAL NOT NULL,
  FOREIGN KEY(image_id) REFERENCES images(image_id) ON DELETE CASCADE);
CREATE TABLE pair_provenance(
  pair_id INTEGER PRIMARY KEY NOT NULL,
  source_flags INTEGER NOT NULL,
  retrieval_score REAL);
CREATE TABLE markers(
  marker_id INTEGER PRIMARY KEY NOT NULL,
  label TEXT NOT NULL,
  type INTEGER NOT NULL,
  world_position BLOB,
  world_position_cov BLOB,
  point3D_id INTEGER NOT NULL,
  enabled INTEGER NOT NULL);
CREATE UNIQUE INDEX index_marker_label ON markers(label);
CREATE TABLE marker_projections(
  marker_id INTEGER NOT NULL,
  image_id INTEGER NOT NULL,
  x REAL NOT NULL,
  y REAL NOT NULL,
  size REAL NOT NULL,
  pinned INTEGER NOT NULL,
  point2D_idx INTEGER NOT NULL DEFAULT 4294967295,
  PRIMARY KEY(marker_id, image_id),
  FOREIGN KEY(marker_id) REFERENCES markers(marker_id) ON DELETE CASCADE,
  FOREIGN KEY(image_id) REFERENCES images(image_id) ON DELETE CASCADE);
CREATE INDEX index_marker_projection_image
  ON marker_projections(image_id);
CREATE TABLE keypoints(
  image_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  FOREIGN KEY(image_id) REFERENCES images(image_id) ON DELETE CASCADE);
CREATE TABLE keypoint_colors(
  image_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  FOREIGN KEY(image_id) REFERENCES keypoints(image_id) ON DELETE CASCADE);
CREATE TABLE descriptors(
  image_id INTEGER PRIMARY KEY NOT NULL,
  type INTEGER NOT NULL,
  type_name TEXT,
  dtype INTEGER,
  dim INTEGER,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  FOREIGN KEY(image_id) REFERENCES images(image_id) ON DELETE CASCADE);
CREATE TABLE matches(
  pair_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB);
CREATE TABLE match_scores(
  pair_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  FOREIGN KEY(pair_id) REFERENCES matches(pair_id) ON DELETE CASCADE);
CREATE TABLE two_view_geometries(
  pair_id INTEGER PRIMARY KEY NOT NULL,
  rows INTEGER NOT NULL,
  cols INTEGER NOT NULL,
  data BLOB,
  config INTEGER NOT NULL,
  F BLOB,
  E BLOB,
  H BLOB,
  qvec BLOB,
  tvec BLOB,
  camera1 BLOB,
  camera2 BLOB);
)SQL";
    static const std::vector<ColmapDbProfileSpec> profiles = {
        {"colmap-3.13.0",
         "0b31f98133b470eae62811b557dc2bcff1e4f9a5",
         0, 3900, false, false, false, false,
         stock_313.c_str(), false},
        {"colmap-4.1.1",
         "a0d785fba74b2664f31edc4a29026a8b27c00f67",
         0, 4010100, true, true, false, false,
         stock_411.c_str(), false},
        {"colmap-main-64805cb870b5",
         "64805cb870b574a569dccc34918d95a2db2b2fee",
         0, 4020000, true, true, true, false,
         stock_current.c_str(), false},
        {"maxx-v1",
         "de15b08a2dba98b55d6ddfb7cedac147838afbb4",
         0x4D415858, 3140003, true, true, true, true,
         maxx.c_str(), true},
    };
    return profiles;
}
