"""Built-in raster-image codec definitions."""

from __future__ import annotations

from sceneio import _core
from sceneio.io._registry.adapters import (
    _file_sink_writer,
    _mmap_reader,
    _mmap_selector_reader,
)
from sceneio.io._registry.model import Codec

IMAGE_CODECS: tuple[Codec, ...] = (
    Codec(
        "netpbm",
        (".ppm", ".pgm", ".pnm"),
        _mmap_reader(_core.read_netpbm),
        _file_sink_writer(_core.write_netpbm),
        record=_core.Image,
        datatype="image",
        magic=(b"P2", b"P3", b"P5", b"P6"),
        read_window=_mmap_selector_reader(_core.read_netpbm_window),
        supported_features=("p2", "p3", "p5", "p6", "uint8", "uint16"),
        unsupported_features=("ascii_window",),
    ),
    Codec(
        "png",
        (".png",),
        _mmap_reader(_core.read_png),
        _file_sink_writer(_core.write_png),
        record=_core.Image,
        datatype="image",
        magic=(b"\x89PNG\r\n\x1a\n",),
        supported_features=(
            "grayscale",
            "rgb",
            "rgba",
            "palette",
            "uint8",
            "uint16",
            "typed_depth_adapter",
        ),
    ),
    Codec(
        "jpeg",
        (".jpg", ".jpeg"),
        _mmap_reader(_core.read_jpeg),
        _file_sink_writer(_core.write_jpeg),
        record=_core.Image,
        datatype="image",
        magic=(b"\xff\xd8\xff",),
        lossy=True,
        supported_features=("baseline", "progressive", "grayscale_read", "rgb"),
        unsupported_features=("cmyk_write", "rgba_write"),
    ),
    Codec(
        "bmp",
        (".bmp",),
        _mmap_reader(_core.read_bmp),
        _file_sink_writer(_core.write_bmp),
        record=_core.Image,
        datatype="image",
        magic=(b"BM",),
        supported_features=(
            "windows_v3_v4_v5",
            "bottom_up",
            "top_down",
            "palette_read",
            "packed_16bit_read",
            "rgb",
            "rgba_bitfields",
        ),
        unsupported_features=(
            "os2",
            "rle4",
            "rle8",
            "embedded_jpeg_png",
            "alphabitfields",
            "grayscale_write",
        ),
    ),
    Codec(
        "tga",
        (".tga",),
        _mmap_reader(_core.read_tga),
        _file_sink_writer(_core.write_tga),
        record=_core.Image,
        datatype="image",
        supported_features=(
            "uncompressed",
            "rle",
            "grayscale",
            "rgb",
            "rgba",
            "palette_read",
            "packed_15_16bit_read",
            "top_bottom_origin",
        ),
        unsupported_features=(
            "right_to_left",
            "interleaving",
            "nonzero_palette_origin",
            "grayscale_alpha",
        ),
    ),
    Codec(
        "hdr",
        (".hdr",),
        _mmap_reader(_core.read_hdr),
        _file_sink_writer(_core.write_hdr),
        record=_core.Image,
        datatype="image",
        magic=(b"#?RADIANCE", b"#?RGBE"),
        lossy=True,
        supported_features=("rgbe", "rle", "float32_rgb"),
    ),
    Codec(
        "exr",
        (".exr",),
        _mmap_reader(_core.read_exr),
        _file_sink_writer(_core.write_exr),
        record=_core.Image,
        datatype="image",
        magic=(b"\x76\x2f\x31\x01",),
        supported_features=(
            "single_channel",
            "rgb",
            "rgba",
            "half_to_float",
            "typed_depth_adapter",
        ),
        unsupported_features=("multipart", "deep", "tiled", "uint_channels"),
    ),
    Codec(
        "webp",
        (".webp",),
        _mmap_reader(_core.read_webp),
        _file_sink_writer(_core.write_webp),
        record=_core.Image,
        datatype="image",
        read_window=_mmap_selector_reader(_core.read_webp_window),
        lossy=True,
        supported_features=("lossless", "lossy", "rgb", "rgba"),
        unsupported_features=("animation", "lossy_window"),
    ),
)
