"""Repository-owned adapters for portable COLMAP ecosystem data."""

from .mapping_input import (
    inspect_mapping_input,
    read_mapping_input,
    write_mapping_input,
)
from .megaloc import (
    inspect_megaloc_artifacts,
    read_megaloc_artifacts,
    write_megaloc_artifacts,
)
from .models import (
    UINT32_MAX,
    UINT64_MAX,
    CharucoBoard,
    CharucoCalibration,
    ColmapAdapterError,
    ExtendedSparseModel,
    IdTags,
    MappingInput,
    MegaLocArtifacts,
    MegaLocImage,
    MegaLocPair,
    RigConfigCamera,
    RigConfiguration,
    SparseExtensions,
    SparseMarker,
    SparseMarkerProjection,
    TimeFrame,
)
from .rig import read_rig_config, write_rig_config
from .sparse import (
    read_extended_sparse_model,
    read_sparse_extensions,
    write_extended_sparse_model,
)
from .text import (
    read_feature_matches,
    read_image_pairs,
    read_sift_features,
    read_similarity_transform,
    read_stock_image_pairs,
    write_feature_matches,
    write_image_pairs,
    write_sift_features,
    write_similarity_transform,
)

__all__ = [
    "UINT32_MAX",
    "UINT64_MAX",
    "CharucoBoard",
    "CharucoCalibration",
    "ColmapAdapterError",
    "ExtendedSparseModel",
    "IdTags",
    "MappingInput",
    "MegaLocArtifacts",
    "MegaLocImage",
    "MegaLocPair",
    "RigConfigCamera",
    "RigConfiguration",
    "SparseExtensions",
    "SparseMarker",
    "SparseMarkerProjection",
    "TimeFrame",
    "inspect_mapping_input",
    "inspect_megaloc_artifacts",
    "read_extended_sparse_model",
    "read_feature_matches",
    "read_image_pairs",
    "read_mapping_input",
    "read_megaloc_artifacts",
    "read_rig_config",
    "read_sift_features",
    "read_similarity_transform",
    "read_sparse_extensions",
    "read_stock_image_pairs",
    "write_extended_sparse_model",
    "write_feature_matches",
    "write_image_pairs",
    "write_mapping_input",
    "write_megaloc_artifacts",
    "write_rig_config",
    "write_sift_features",
    "write_similarity_transform",
]
