"""Generate the C++ camera-model lookup from SceneIO's Python manifest."""

from __future__ import annotations

import argparse
import runpy
from pathlib import Path


def _render(manifest: Path) -> str:
    namespace = runpy.run_path(str(manifest))
    specs = namespace.get("CAMERA_MODEL_SPECS")
    if not isinstance(specs, tuple) or not specs:
        raise ValueError("CAMERA_MODEL_SPECS must be a nonempty tuple")

    cases: list[str] = []
    for expected_id, spec in enumerate(specs):
        if not isinstance(spec, tuple) or len(spec) != 3:
            raise ValueError(f"camera model {expected_id} must be an (id, name, params) tuple")
        model_id, name, params = spec
        if model_id != expected_id:
            raise ValueError("camera-model ids must be contiguous and ordered from zero")
        if not isinstance(name, str) or not name or '"' in name:
            raise ValueError(f"camera model {model_id} has an invalid C++ name")
        if not isinstance(params, tuple) or not params:
            raise ValueError(f"camera model {model_id} must declare parameters")
        cases.append(f'        case {model_id}: return {{"{name}", {len(params)}}};')

    return "\n".join(
        (
            "// Generated by tools/generate_camera_models.py; do not edit.",
            "#pragma once",
            "",
            "inline ModelInfo colmap_model_info(int id) {",
            "    switch (id) {",
            *cases,
            "        default:",
            "            throw std::invalid_argument(",
            '                "COLMAP: unknown camera model id " + std::to_string(id));',
            "    }",
            "}",
            "",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the output is missing or stale",
    )
    args = parser.parse_args()
    rendered = _render(args.manifest.resolve())
    output = args.output.resolve()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"generated camera-model header is stale: {output}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
